project:
  name: sample

spring:
  profiles:
    active: local     # default profile
    include:
      - core
    group:
      local: core-${spring.profiles.active}
      dev: core-${spring.profiles.active}
      prod: core-${spring.profiles.active}

server:
  mq-hosts:
    - v-host: contract
      user: contract
      pass: contract
      listener:
        concurrent-consumers: 2 # 리스너 실행에 사용할 최소 스레드 수 설정
        retry:
          enabled: true         # 재시도를 활성화할지 여부, (기본값 false 비활성화)
          initial-interval: 1   # 첫번째 전송과 두번쨰 전송 사이의 시간 간격 (기본값 1초)
          max-attempts: 3       # 메시지 전송 재시도 횟수 (기본값 3)
          max-interval: 5       # 메시지 전송 재시도 간 최대 간격 (기본값 10초)
          multiplier: 2         # 이전 재시도 간격에서 횟수가 증가될 때마다 가중되는 비율 (기본값 1.0)
      publisher:
        enabled: true
        confirms: true

jwt:
  request:
    ignore.module: >
      /sample/ignore/get,
      /sample/ignore/get/sample
    permit.module: >
      /sample/api/base/notoken/**
