spring:
  config:
    activate:
      on-profile: local

server:
  port: 9512

logging:
  file:
    path: C:\logs\gs\rpa\

datasources:
  - name: gs_rpa
    base-package: kr.fingate.gs.*.**.dao
    aop-execution: kr.fingate.gs..service.*.*(..)
    data-source:
      driverClassName: org.mariadb.jdbc.Driver
      jdbcUrl: jdbc:mariadb://192.168.0.16:3306/gs_rpa?characterEncoding=UTF-8&serverTimezone=UTC&noAccessToProcedureBodies=true&useSSL=false&allowMultiQueries=true&autoReconnect=true
      username: gs_rpa
      password: fingate123!
      maximumPoolSize: 30  # max pool size (엑셀파일 참조)
      minimumIdle: 15  # min pool size (엑셀파일 참조)
      autoCommit: false
      connectionTimeout: 30000
