datasources:
  - name: gs_auth
    base-package: kr.fingate.gs.*.**.dao
    aop-execution: kr.fingate.gs..service.*.*(..)
    data-source:
      driverClassName: org.mariadb.jdbc.Driver
      jdbcUrl: jdbc:mariadb://192.168.0.16:3306/gs_prdct
      username: gs_prdct
      password: fingate123!
      maximumPoolSize: 30  # max pool size (엑셀파일 참조)
      minimumIdle: 15  # min pool size (엑셀파일 참조)
      autoCommit: false
      connectionTimeout: 30000

logging:
  file:
    path: /home/fingate/logs/logback/prdct/