datasources:
  - name: gs_auth
    base-package: kr.fingate.gs.*.**.dao
    aop-execution: kr.fingate.gs..service.*.*(..)
    data-source:
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbcUrl: jdbc:log4jdbc:oracle:thin:@192.168.0.20:1521/FREE
      username: GBCMSNUSER
      password: finora615cmsn
      maximumPoolSize: 30  # max pool size (엑셀파일 참조)
      minimumIdle: 15  # min pool size (엑셀파일 참조)
      autoCommit: false
      connectionTimeout: 30000

logging:
  file:
    path: C:\logs\gs\cmsn\