project:
  name: rpa

spring:
  profiles:
    active: local     # default profile
    include:
      - core
      - common
    group:
      local: core-${spring.profiles.active},common-${spring.profiles.active}
      dev: core-${spring.profiles.active},common-${spring.profiles.active}
      prod: core-${spring.profiles.active},common-${spring.profiles.active}

pagehelper:
  helper-dialect: mariadb

jwt:
  request:
    ignore.module: >
      /rpa/ignore/get,
      /rpa/ignore/get/rpa
      /rpa/api/**
    permit.module: >
#      /rpa/api/**